import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Barlow } from 'next/font/google'
import './style/globals.css'
import Header from './component/header/Header'
import Footer from './component/footer/Footer'
import FooterMobile from './component/footer/FooterMobile'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const barlow = Barlow({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400','500', '600', '700', '800', '900'],
  variable: '--font-barlow'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${barlow.variable} font-barlow`}>
        <Header />
        {children}
        <Footer/>
        <FooterMobile/>
      </body>
    </html>
  )
}
